- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- IMAGE_MAINTAINER_AGREEMENT.md
@valentincanonical can you please have a look?
> docs(CONTRIBUTING): add CONTRIBUTING, CoC and Maintainer Agreement

- README.md
---
Add reference information and examples into the README.md.
This includes general information as well as the specification around Trigger files and the overall organisation of OCI images within the repo.
This addresses the feedback received in https://github.com/canonical/oci-factory/issues/8.
Fixes https://github.com/canonical/oci-factory/issues/8
---
*Picture of a cool ROCK:*
> docs(README): complete README with reference info

- .github/ISSUE_TEMPLATE/--onboarding.yaml
- .github/ISSUE_TEMPLATE/config.yml
- README.md
---
- adds a useful link and configures how new issues can be created
- adds a new issue template for allowing Maintainers to request the onboarding of new images
- update the README accordingly
> feat: image onboarding issue template

- oci/traefik/.trivyignore
> feat: add trivyignore to traefik

- oci/mimir/.trivyignore
> feat: add trivyignore to mimir

- oci/loki/.trivyignore
> feat: add trivyignore to loki

- oci/grafana/.trivyignore
> feat: add trivyignore to grafana

- .github/ISSUE_TEMPLATE/--onboarding.yaml
- .github/workflows/Image.yaml
- .github/workflows/Tests.yaml
- IMAGE_MAINTAINER_AGREEMENT.md
- README.md
- oci/mock-rock/_releases.json
- src/image/utils/schema/triggers.py
- src/uploads/infer_image_track.py
---
Remove dockerfile-based builds.
---
*Picture of a cool ROCK:*
> Remove support for dockerfile-based builds

- oci/kafka/image.yaml
---
Updating the commit id following Kafka rock release on its repository
> [DPE-3231] Use official commit id for Kafka Rock

- oci/karma/contacts.yaml
- oci/karma/documentation.yaml
- oci/karma/image.yaml
---
This PR adds the Karma ROCK to the oci-factory.
#165
> feat: add karma rock

- oci/tempo/contacts.yaml
- oci/tempo/documentation.yaml
- oci/tempo/image.yaml
---
This PR adds the Tempo ROCK to the OCI factory.
#171 
---
> feat: Add tempo rock

- oci/kafka/documentation.yaml
---
Small fix of the docs for Kafka image
> (chore) fix new line in bash kafka docs

- oci/python/image.yaml
---
New version, 3.12, of the python rock
> feat: release new python version, 3.12

- oci/zookeeper/image.yaml
Updating EOL for ZooKeeper image
> (chore) Update EOL commitments on ZooKeeper image

- oci/kafka/image.yaml
---
Updating EOL for Kafka and ZooKeeper images in order to trigger builds as usual.
> (chore) Update EOL commitments on Kafka image

- src/workflow-engine/charms/temporal-worker/oci_factory/activities/find_images_to_update.py
---
Similar to #194 , but of a different fashion. To be discussed.
> fix: remove trigger for img w/o release within eol

- oci/mock-rock/_releases.json
- src/image/requirements.sh
---
Fix `src/image/requirements.sh` so the dependency `logging_common.py` from `cpc_build_tools` is correctly copied.
https://github.com/ubuntu-rocks/dotnet/issues/616
> Fix cpc build tools new deps

- oci/mock-rock/_releases.json
- src/tests/get_released_revisions.py
---
This PR fixes the failures in the continuous testing pipeline.
- ROCKS-1310
- https://github.com/canonical/oci-factory/actions/runs/9900976084/job/27352608490
> Fix Continuous Testing Pipeline Failure

- oci/python/image.yaml
---
This PR adds OCI-factory support for Python 3.10.
> feat: add python 3.10

- oci/python/image.yaml
---
Adds arm64 for all python rocks
---
> chore: build python rocks for arm64

- oci/hydra/.trivyignore
- oci/hydra/contacts.yaml
- oci/hydra/documentation.yaml
- oci/hydra/image.yaml
---
- adding Hydra to oci-factory
-----
> feat: add hydra to oci-factory

- oci/identity-platform-admin-ui/contacts.yaml
- oci/identity-platform-admin-ui/documentation.yaml
- oci/identity-platform-admin-ui/image.yaml
---
- Add admin-ui to oci-factory
-----
> feat: add admin-ui to oci-factory

- oci/mock-rock/_releases.json
- oci/mock-rock/image.yaml
Features included in this PR:
- Update oci/mock-rock/image.yaml to not release EOL images.
> fix: Correct Bad mock-rock Release Config

- oci/parca/contacts.yaml
- oci/parca/documentation.yaml
- oci/parca/image.yaml
---
Add the parca rock to oci-factory, in its latest available version. 
---
> feat: Add parca rock

- oci/jre/contacts.yaml
- oci/jre/documentation.yaml
---
- Use Ubuntu Toolchains channel rather than general Foundations
- Fix documentation formatting:  add empty lines before code blocks.
---
> fix: update contacts and documentation for jre/21 rock

- oci/jre/documentation.yaml
---
- rename application to jre 
- drop auto-generated header section
---
> doc: update jre21 header documentation

- oci/mock-rock/_releases.json
- src/docs/generate_oci_doc_yaml.py
---
Skips the digests with non-canonical tags when releasing the documentation.
https://github.com/canonical/oci-factory/actions/runs/13919820106/job/38950243792
> fix(ci/doc): skip digest with non canonical tags

- .github/actions/upload-rock/action.yml
- .github/workflows/Image.yaml
- oci/mock-rock/_releases.json
---
This PR adds a new action to upload oci-images to a container registry. This action will be used by the [rockcrafters](https://github.com/rockcrafters/) org to publish images to GHCR.
> Feat: Upload-Rock Action

- .github/workflows/Vulnerability-Scan.yaml
- oci/mock-rock/_releases.json
---
This PR adds the use of `.trivyignore` to the `Vulnerability Scan` workflow to exclude the ignored vulnerabilities for daily testing.
https://github.com/canonical/oci-factory/actions/runs/14049642320/attempts/1#summary-39338078760
> fix(ci): use trivyignore for cont. testing

- oci/mysql/contacts.yaml
---
- Add a `maintainer` for mysql rock automation
---
> mysql maintainer bot account

- oci/nginx-prometheus-exporter/.trivyignore
- oci/nginx-prometheus-exporter/contacts.yaml
- oci/nginx-prometheus-exporter/documentation.yaml
- oci/nginx-prometheus-exporter/image.yaml
---
Adds a release of the nginx-prometheus-exporter rock to OCI factory
#410 
---
> nginx prom exporter oci v1

- .github/workflows/Image.yaml
- oci/mock-rock/_releases.json
---
This PR makes sure that the CI will notify the workflow failures and cancellations in all the jobs.
https://github.com/canonical/oci-factory/actions/runs/14467566103/job/40573455393
> feat(ci): notify on every failure and cancellation

- oci/mock-rock/_releases.json
- oci/mock-rock/image.yaml
- src/image/prepare_single_image_build_matrix.py
- src/image/release.py
- src/image/utils/eol_utils.py
---
https://github.com/canonical/oci-factory/actions/runs/14897325314
---
> fix(ci): support aliased track with base info

- oci/pyroscope/contacts.yaml
- oci/pyroscope/documentation.yaml
- oci/pyroscope/image.yaml
---
This pull request adds Pyroscope, a profiling backend by Grafana, in its latest available version.
Context: #479 .
---
> Add pyroscope

- oci/dotnet-deps/contacts.yaml
- oci/dotnet-deps/documentation.yaml
- oci/dotnet-deps/image.yaml
---
This PR adds the dotnet-runtime:9.0-25.04_edge.
#516
> feat: add dotnet-deps:9.0-25.04_edge

- .github/actions/check-trivyignore/action.yaml
- oci/mock-rock/_releases.json
---
This PR provides a more robuster jq query sentence that reduces false positives on redundant `.trivyignore` entries.
N/A
> feat(ci): robuster jq query on trivy json

- oci/temporal-server/.trivyignore
- oci/temporal-server/contacts.yaml
- oci/temporal-server/documentation.yaml
- oci/temporal-server/image.yaml
---
This PR introduces temporal-server rock, which is an image that runs the temporal server (where all services are run in a single application)
#506 
---
> feat: onboard temporal-server

- oci/dotnet-runtime/documentation.yaml
> doc(dotnet-runtime): override EOL

- oci/dotnet-aspnet/documentation.yaml
> doc(dotnet-aspnet): override EOL

- oci/dotnet-deps/documentation.yaml
> doc(dotnet-deps): override EOL

- .github/workflows/Release.yaml
> fix(ci): create dir for new image in _releases branch

- .github/actions/fetch-releases-json/action.yaml
---
This PR fixes the issue in https://github.com/canonical/oci-factory/pull/558#discussion_r2273434554
---
> fix(ci): find cmd in fetch-releases-json action

- oci/node/documentation.yaml
- oci/node/image.yaml
---
Updating the nodejs image following the latest refactor of the repository. In terms of the rockcraft.yaml, this only changes the `deb-security-manifest` which is now using the one from https://github.com/canonical/rocks-security-manifest
---
<p align="center">
</p>
> feat(node): update nodejs image

- tools/workflow-engine/charms/temporal-worker/oci_factory/activities/find_images_to_update.py
---
This PR allows the rebuild script to look into the split `_releases.json` files from the `_releases` branch.
---
> chore: clone releases branch for rebuild

- oci/grafana/.trivyignore
- oci/grafana/image.yaml
---
Add a new version to the Grafana rock. Supersedes https://github.com/canonical/oci-factory/pull/548
---
*Picture of a cool rock:* 🪨
> feat: add new version for Grafana 12

- oci/php/documentation.yaml
- oci/php/image.yaml
> fix(php): update EOL for 25.04

- oci/loki/.trivyignore
- oci/loki/image.yaml
---
Add 2.9.15 with correct EOL :)
> feat: add loki v2.9.15
