- oci/charmed-opensearch/image.yaml
This PR essentially bumps the OpenSearch version to `2.9.0` 
===> some CVEs are expected to be fixed by this upgrade
Question: How does this play out with versions? I would like the previous version `2.8.0` to also be published
> Charmed OpenSearch - bump version to 2.9.0

- oci/prometheus/contacts.yaml
- oci/prometheus/image.yaml
---
Remove Prometheus 2.45.0 as it's not passing the vulnerability check, and fix the Mattermost channel ID with the correct one.
---
*Picture of a cool ROCK:*
> fix: remove prometheus 2.45.0 and fix mattermost id

- oci/mimir/contacts.yaml
- oci/mimir/documentation.yaml
- oci/mimir/image.yaml
---
This PR adds the **Mimir** ROCK to the oci-factory.
#46
> feat: add mimir rock

- oci/traefik/contacts.yaml
- oci/traefik/documentation.yaml
- oci/traefik/image.yaml
---
This PR adds the **Traefik** ROCK to the oci-factory
#47
> feat: add traefik-rock

- oci/alertmanager/contacts.yaml
- oci/alertmanager/documentation.yaml
- oci/alertmanager/image.yaml
---
This PR adds the Alertmanager ROCK to the oci-factory.
Please note that this should go to a new `alertmanager` repository that's yet to be created. There currently exists a [prometheus-alertmanager](https://hub.docker.com/r/ubuntu/prometheus-alertmanager) repository, but that one should be deprecated.
#42
> feat: add alertmanager rock

- oci/loki/contacts.yaml
- oci/loki/documentation.yaml
- oci/loki/image.yaml
---
This PR adds the Loki ROCK to the oci-factory.
#45
> feat: add loki rock

- oci/grafana/contacts.yaml
- oci/grafana/documentation.yaml
- oci/grafana/image.yaml
---
This PR adds the Grafana ROCK to the **oci-factory**.
#43
> feat: add grafana rock

- oci/alertmanager/.trivyignore
---
The current upstream code base is suffering from a potential HTTP/2 DoS vulnerability in the Golang standard libraries and is still pending a dependency upgrade.
- https://github.com/prometheus/alertmanager/discussions/3471
---
*Picture of a cool ROCK:*
> Ignore upstream CVE in Alertmanager pending a fix

- .github/base_digests/20.04
- .github/base_digests/22.04
- .github/workflows/Image.yaml
- .github/workflows/_Auto-updates.yaml
- renovate.json
- src/workflow-engine/charms/temporal-worker/oci_factory/activities/find_images_to_update.py
---
Add standalone script to run auto updates for images, based on new Ubuntu container bases.
> feat(ci): enable GH-contained auto-updates

- oci/alertmanager/.trivyignore
> feat: update trivyignore for alertmanager

- oci/prometheus-pushgateway/.trivyignore
- oci/prometheus-pushgateway/contacts.yaml
- oci/prometheus-pushgateway/documentation.yaml
- oci/prometheus-pushgateway/image.yaml
---
This PR adds the Prometheus Pushgateway ROCK to the oci-factory.
Please note that this should go to a new `prometheus-pushgateway` repository that's yet to be created.
#75
> feat: add prometheus-pushgateway rock

- .github/workflows/Documentation.yaml
- .github/workflows/Image.yaml
- .github/workflows/Release.yaml
- .github/workflows/_Test-OCI-Factory.yaml
- IMAGE_MAINTAINER_AGREEMENT.md
- oci/mock-rock/_releases.json
---
Currently, workflows in `Documentation.yaml`, `Image.yaml` and `Release.yaml` are dispatched via `mathze/workflow-dispatch-action`. We’ll still still need the dispatch on some, at least for those that the Temporal workflows will trigger. But internally (on PRs and commits), those workflows are to be made callable.
> make github workflows callable instead of using workflow-dispatch-action

- .github/workflows/Documentation.yaml
- .github/workflows/Image.yaml
- oci/mock-rock/_releases.json
---
Follow up on merged PR#123, since _Tests workflow didn't seem to pass after the merge.
This changes the check for worflow dispatch/call from relying on `github.event_name` to check whether `inputs.oci-image-name` exists, as the latter is always provided by a workflow dispatch/call.
The issue arised from the fact the the called workflows are inherting the event name from their calling parents, so `github.event_name` isn't a fit anymore for the current purpose.
> fix: replace workflow call/dispatch check with more reliable tests

- oci/python/contacts.yaml
- oci/python/documentation.yaml
- oci/python/image.yaml
---
This PR adds the oci-factory configurations for a new chiselled Python3.8 rock.
> feat: add chiselled Python 3.8 rock

- oci/mock-rock/_releases.json
- src/workflow-engine/charms/temporal-worker/oci_factory/activities/find_images_to_update.py
---
Fix issue in https://github.com/canonical/oci-factory/actions/runs/8073081089/job/22056099446 caused by eol value being misused as a revisions dict.
> fix: extract revision numbers only from the revision dicts

- .github/workflows/Image.yaml
- .github/workflows/_Test-OCI-Factory.yaml
- oci/mock-rock/_releases.json
---
- bumped the download-artifact action in the provenance job (which was failing to fetch the workflow's artifacts)
- fixed a race condition: in the previous PR, the Image.yaml and _Test workflows would be triggered at the same time, which would cause a race condition to the `_release.json` file. This PR makes sure the Image.yaml doesn't run for the mock-rock, cause it should be called by the _Test workflow anyway
https://github.com/canonical/oci-factory/actions/runs/8187580397/job/22390383561
> fix: race condition between Image and _Test

- oci/zookeeper/.trivyignore
- oci/zookeeper/contacts.yaml
- oci/zookeeper/documentation.yaml
- oci/zookeeper/image.yaml
---
We have recently created a Rock for packaging Apache ZooKeeper [here](https://github.com/canonical/zookeeper-rock/pull/1). The binaries are the same as the ones used in Charmed ZooKeeper images, but here we just reduce only to the Apache ZooKeeper, leaving outside all the extra components and dependencies. 
The idea of the image would be to replace the current Apache ZooKeeper images in DockerHub that are not integrated with Rock and OCI Factory pipeline.
> [DPE-3232] Apache ZooKeeper <> OCI Factory Integration

- oci/mock-rock/_releases.json
- src/docs/generate_oci_doc_yaml.py
- src/image/merge_release_info.py
- src/image/prepare_single_image_build_matrix.py
- src/image/release.py
- src/tests/requirements.txt
- src/uploads/infer_image_track.py
---
The default python YAML parser that we uses to parse various yaml files consider all numeric values in the yaml values as integers or float as long as they are not enclosed by quotes.
That means that a field like `version: 2.3` would get the value of `2.3` as a float and not as string.
However, our python classes are expecting all values to be strings, because those values are not guaranteed to be numerical in all cases (i.e. `version` value can contain letters too).
The implemented solution in this PR was:
- add a common module and import it in all other modules that uses the yaml parser
- in the common module, make the default parsing behavior of numerical values construct them as strings
> Parse numerical strings in yaml files as strings

- oci/mock-rock/_releases.json
- src/docs/generate_oci_doc_yaml.py
---
If a channel has an associated EOL, make sure it is reflected in the registry docs.
Here's a successful run: https://hub.docker.com/r/rocksdev/mock-rock, from https://github.com/canonical/oci-factory/actions/runs/9303807030/job/25606973889
---
> feat: add EOL to doc generation

- .github/workflows/Image.yaml
- oci/mock-rock/_releases.json
---
This PR fix the issue that the `prepare-upload` job is not protected by the triggering condition, causing unnecessary increments of revision numbers if the workflow is not expected to run the `upload` job.
> fix: move upload trigger condition to prepare-upload

- .github/workflows/Documentation.yaml
- .github/workflows/Release.yaml
- oci/mock-rock/_releases.json
---
This PR fixes the issue when a new track is released with the OCI Factory, the EOL field is not properly set after the first run of the `Image.yaml` workflow. The cause of the problem is the default checkout refs in the called workflow `Documentation.yaml` is the HEAD of main when the `Image.yaml` workflow is dispatched, in which the updates to `_releases.json` in the `Release.yaml` workflow is not included yet. The PR passes the commit SHA that contains the updates to `_releases.json` from the `Release.yaml` workflow, and forces the `Documentation.yaml` workflow to checkout to this commit when generating the document yaml.
Manually trigger the `Documentation.yaml` workflow one more time after the `Image.yaml` workflow completes with success. …
> fix(ci): pass commit sha to force doc wf checkout to newest main

- .github/workflows/Release.yaml
- oci/mock-rock/_releases.json
---
This PR changes the use of the token passed to the `actions-x/commit` action to allow the changes of `_releases.json` files to the protected branches to be commited.
[Workflow run](https://github.com/canonical/oci-factory/actions/runs/10503841228/job/29099351534)
> fix: commit to protected branch with ROCKSBOT_TOKEN

- examples/mock-rock/1.2/rockcraft.yaml
- oci/mock-rock/image.yaml
This PR is to remove Launchpad CI as a requirement to build the mock rocks.
Currently Launchpad is used to build a ppc64el arch rock. When test builds of mock-rock are triggered, lpci jobs builds take a long time to complete, and seem to fail (timeout) more often than they succeed. This makes testing changes more difficult. 
We mitigate this issue by removing ppc64el arch support form mock-rock 1.2.
> Remove Launchpad CI dependency from Mock Rocks

- oci/mock-rock/image.yaml
When #234 was merged, the subsequent squash removed the githash that was required for to build Mock Rock 1.2.  
Here we are updating that githash again, to a commit already in main to fix the mock-rock build.
> Repair OCI Factory Mock Rock Builds

- .github/workflows/Build-Rock.yaml
- oci/mock-rock/_releases.json
---
This PR fixes the missing "checkout" in the Build Rock workflow, which causes the workflow to fail unexpectedly. This but is not captured by the testing workflow either, as the `mock-rock` lives inside the `oci-factory` repo, which conceals this bug under the water.
https://github.com/canonical/oci-factory/actions/runs/10920792896/job/30311462832
https://github.com/canonical/oci-factory/actions/runs/10945495302/job/30389858407#step:3:1
> fix: checkout oci-factory repo before actor validation

- .github/base_digests/24.04
---
Since now we have at least on Noble-based rock here, let's get that under Renovate's radar as well.
> feat: add 24.04 to Renovate's radar

- tools/cli-client/internals/cli/cli_main.go
- tools/cli-client/internals/trigger/build_metadata.go
- tools/cli-client/internals/trigger/build_metadata_test.go
---
This PR fixes the following issues:
1. The CLI client is giving false positive results detecting non-interactive terminals.
2. The CLI client dumps stack traceback when the regex fails to match a repo remote URL that does not belong to Canonical.
> Fix CLI Client Handling Non-Interactive Terminal and Error Message for Non-Canonical Repo

- .github/workflows/Build-Rock.yaml
- .github/workflows/Image.yaml
- .github/workflows/Tests.yaml
- .github/workflows/Vulnerability-Scan.yaml
- oci/mock-rock/_releases.json
---
According to the GitHub [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflows-in-forked-repositories), secrets are not passed to the runner when a workflow is triggered from a forked repository. Therefore, for forked PR, the actor validation will always fail. To cope with this issue, we allow the bypassing of actor validation for the Image, Build-Rock, Tests and Vulnerability-Scan workflows triggered with a forked pull request. 
More security thought: The external user's PR workflow will only run upon approval by the repo's maintainer, so the chance of exploiting is considered low. The external user's PR will neither trigger Upload and Release workflows nor have …
> Bypass actor validation for Image, Build, Test, Vul-Scan workflow triggered by forked PRs

- oci/kratos/.trivyignore
- oci/kratos/contacts.yaml
- oci/kratos/documentation.yaml
- oci/kratos/image.yaml
---
- adding Kratos to oci-factory
-----
> feat: add kratos to oci-factory

- oci/identity-platform-login-ui/contacts.yaml
- oci/identity-platform-login-ui/documentation.yaml
- oci/identity-platform-login-ui/image.yaml
---
- adding Login UI to oci-factory
-----
> feat: add login-ui to oci-factory

- oci/identity-platform-admin-ui/contacts.yaml
adding `canonical-iam` as maintainer for `admin-ui`
split from #274
> fix: add canonical-iam as maintainer to use oci-factory cli on admin-ui

- tools/cli-client/internals/trigger/build_metadata.go
- tools/cli-client/internals/trigger/build_metadata_test.go
---
This is a fix for: https://github.com/canonical/oci-factory/actions/runs/11480615194/job/31949441994
> fix(cli-client): empty directories cause CI validation error

- .github/workflows/Vulnerability-Scan.yaml
- oci/mock-rock/_releases.json
---
This change fixes the issue that vulnerability GH issues are created when the PR to add new images are not merged into `main` yet. We should create issues for the oci images only when they are already in the `main` branch since the new images with failing vulnerability scanning results should not be merged into `main`.
Workflow run: https://github.com/canonical/oci-factory/actions/runs/11342692546/job/31546152898?pr=262
---
> Do not create issues on vul scan failures when triggered by pull requests

- oci/hydra/contacts.yaml
adding canonical-iam as maintainer for hydra
split from https://github.com/canonical/oci-factory/pull/274
> fix: add canonical-iam as maintainer to use oci-factory cli on hydra

- oci/identity-platform-login-ui/contacts.yaml
adding canonical-iam as maintainer for login-ui
split from https://github.com/canonical/oci-factory/pull/274
> fix: add canonical-iam as maintainer to use oci-factory cli on login-ui

- .github/workflows/Vulnerability-Scan.yaml
- oci/mock-rock/_releases.json
---
Features in this PR:
- use alternate trivy-db registry to mitigate TOOMANYREQUESTS issue (see: https://github.com/canonical/oci-factory/actions/runs/11741955720/job/32712019963?pr=272)
> fix: add alternate trivy db sources

- README.md
- oci/mock-rock/contacts.yaml
- tools/cli-client/README.md
---
This PR adds the descriptions of the `maintainers` field in the `contacts.yaml` file and corresponding onboarding instructions for adding the maintainers.
---
> Update docs for contacts.yaml

- renovate.json
---
Wildcard is used in the `renovate.json` to include 24.04 into the renovatebot. This also allows the scalability of future releases added to `.github/base_digests`.
> Use wildcard in renovate.json to include 24.04

- oci/mock-rock/contacts.yaml
---
`renovate[bot]` is added to the `maintainers` list of the `mock-rock` to enable the renovation of dependencies of the OCI Factory itself.
https://github.com/canonical/oci-factory/actions/runs/12105641691/job/33775903985?pr=297
> chore: add renovatebot to maintainers of mock-rock

- .github/actions/validate-actor/validate-actor.sh
- oci/mock-rock/_releases.json
- oci/mock-rock/contacts.yaml
---
This follows the PR #298 to resolve the failed workflows caused by renovatebot's not being authorised to trigger the `_Test-OCI-Factory` workflow when renovating dependencies of the workflow itself.
> fix(ci): add escapes for [ and ] to allow renovatebot trigger mock-rock

- .github/workflows/Test-Rock.yaml
- .github/workflows/Vulnerability-Scan.yaml
- .github/workflows/_Test-OCI-Factory.yaml
- oci/mock-rock/_releases.json
- oci/mock-rock/contacts.yaml
The conditionals to toggle jobs in the Test-Rock workflow were missing. As a consequence all jobs are executed all the time. This PR adds the conditionals back.
> Fix: add missing conditionals to optional jobs in test rock

- oci/python/image.yaml
---
Add the Chisel manifest to all Python rocks.
Related change: https://github.com/canonical/chiselled-python/commit/4f4d52540d7be7902bc4232ef51a16f42ec7d60a
> feat: add Chisel manifest to Python rocks

- .github/workflows/_Test-OCI-Factory.yaml
- oci/mock-rock/_releases.json
- src/image/prepare_single_image_build_matrix.py
- tests/data/image_all_eol_tracks.yaml
- tests/data/image_all_eol_tracks_with_release.yaml
- tests/data/image_no_track_releases.yaml
- tests/data/image_single_track_release.yaml
- tests/data/image_with_release.yaml
- tests/data/image_without_release.yaml
- tests/integration/test_prepare_single_image_build_matrix.py
---
Included in this PR:
- fix for determining if there are builds to execute for image trigger files
- tests to check behavior of this change
> fix: release identification in prepare_single_image_build_matrix.py

- oci/mock-rock/_releases.json
- oci/prometheus/_releases.json
- src/image/define_image_revision.sh
- src/image/get_canonical_tags_from_swift.sh
- src/uploads/swift_lockfile_lock.sh
- src/uploads/swift_lockfile_unlock.sh
- tools/workflow-engine/charms/temporal-worker/oci_factory/activities/find_images_to_update.py
This PR fixes the recent bug in OCI-Factory where incorrect revision data was selected causing an error. Previously the start of the image name was selected, creating collisions between images like grafana and grafana-agent. This PR ensure the full image name is matched.
> Fix image name collision in Swift

- .github/workflows/Test-Rock.yaml
- .github/workflows/Vulnerability-Scan.yaml
- oci/mock-rock/_releases.json
Included in this PR:
- remove GitHub summary vulnerability report from .github/workflows/Vulnerability-Scan.yaml and add it to .github/workflows/Test-Rock.yaml so the report is published globally.
> Relocate GitHub Summary Vulnerability Report

- .github/workflows/Build-Rock.yaml
- oci/mock-rock/_releases.json
---
This is used to overcome the compliance issues
wrt using self-hosted runners within PRs
Ref: https://github.com/canonical/oci-factory/actions/runs/12765151616/job/35578834432?pr=306
> fix(ci): only use GH runners for PRs

- .github/workflows/_CLI-Client.yaml
- oci/mock-rock/_releases.json
---
Bump `actions/upload-artifact@v3` to `v4`, since `v3` is deprecated.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
---
> chore(ci): bump upload-artifact to v4

- .github/workflows/Test-Rock.yaml
- oci/mock-rock/_releases.json
---
This PR allows the Test-Rock workflow to test rocks using [entrypoint services](https://documentation.ubuntu.com/rockcraft/en/latest/reference/rockcraft.yaml.html#entrypoint-service) as the entrypoint.
Current black-box testing workflow gets stuck in infinite loops in this scenarios.
https://github.com/canonical/oci-factory/actions/runs/13135426670/job/36650178857?pr=342
- Black-box testing mock-rock with "entrypoint-service": https://github.com/canonical/oci-factory/actions/runs/13178150156/job/36782455844#step:7:17
- Black-box testing mock-rock with normal pebble entrypoint: https://github.com/canonical/oci-factory/actions/runs/13178315059/job/36783170764#step:6:17
> Allow black-box test on non-pebble entrypoint

- oci/valkey/image.yaml
Update the channel tag for Valkey from `edge` to `stable` and update the support period according to the LTS of 24.04.
> stable release for valkey with LTS support

- oci/opentelemetry-collector/.trivyignore
- oci/opentelemetry-collector/contacts.yaml
- oci/opentelemetry-collector/documentation.yaml
- oci/opentelemetry-collector/image.yaml
---
#333
---
*Picture of a cool rock:* 🪨
> feat: onboard opentelemetry-collector

- oci/valkey/documentation.yaml
---
I have removed the suffix `_edge` from the command in the docs
> Valkey - remove "edge" from command in docs

- oci/istio-pilot/contacts.yaml
- oci/istio-pilot/documentation.yaml
- oci/istio-pilot/image.yaml
---
This PR adds the istio-pilot ROCK to the OCI factory.
This Rock uses an `entrypoint service`, as Istio launches the container with arguments that are resolved at deploy-time. This the rock needs to be interchangeable with the upstream OCI, we can't really change this without making the rock unusable outside of the charm context.
To tackle I have included all subcommands/flags that could be passed when using this rock along with their default values in the rock's `documentation.yaml`.
#361
> adding pilot rock

- .github/workflows/CLA-Check.yaml
- .github/workflows/Test-Rock.yaml
- oci/mock-rock/_releases.json
---
Bump jobs running on Ubuntu 20.04 runner to 22.04, and remove 20.04 from `Test-Rock` runner os matrix.
https://github.com/actions/runner-images/issues/11101
> chore(ci): bump and remove runs on ubuntu 20.04

- .github/workflows/Build-Rock.yaml
- oci/mock-rock/_releases.json
---
The compliance setups have changed in canonical/repo-policy-compliance. Trying to restore the use of self-hosted runners to enable onboarding images that support archs other than `amd64`.
Workflow on self-hosted arm64 runner triggered by PR: https://github.com/canonical/oci-factory/actions/runs/13674237778/job/38231123800?pr=379
https://github.com/canonical/repo-policy-compliance/pull/1905
> fix(ci): use self-hosted runners for PRs

- .github/workflows/Documentation.yaml
- .github/workflows/Image.yaml
- .github/workflows/PR-Validator.yaml
- .github/workflows/Release.yaml
- .github/workflows/_Auto-updates.yaml
---
Address https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/ by pinning the action to a known safe sha.
https://github.com/tj-actions/changed-files/issues/2463
> fix(ci): address CVE-2025-30066

- oci/jre/contacts.yaml
---
In order to avoid spamming discussion channels, make a dedicated notification channel.
---
> feat: use dedicated mattermost channel for jre rock notifications

- oci/glauth/_releases.json
- oci/jre/documentation.yaml
- oci/jre/image.yaml
---
This PR adds chiselled jre runtime for openjdk 11.
---
> feat: add jre/11_edge to oci-factory

- oci/jre/image.yaml
---
Updated JRE 11 EOL date as per Oracle Roadmap[1]
[1] https://www.oracle.com/in/java/technologies/java-se-support-roadmap.html
---
> fix: update jre 11 EOL date

- oci/mock-rock/_releases.json
- src/image/release.py
---
This PR fixes the `KeyError` when the custom image trigger passed to the `Release` workflow does not have a `release` field in the `upload` section.
https://github.com/canonical/oci-factory/actions/runs/14266265582/job/39989676808
> fix(ci): crash when upload does not have release in trigger

- .github/workflows/Test-Rock.yaml
- oci/mock-rock/_releases.json
---
OCI Factory has been using `dive` to test the efficiency of the rocks since the very beginning. In some cases (i.e. including the `base-passwd_data` in the parts, and defining `run-user: _daemon_`), `dive` will fail the `highestUserWastedPercent` tests due to modified files in the second layer. However, since the users have no control over the layering when a rock is built with `rockcraft`, we therefore allow the rocks to fail the `highestUserWastedPercent` test, which can serve as a notification that the layering can be improved, but still enforce the `lowestEfficiency` test to pass before a rock can be released.
A minimal case to reproduce this:
```
name: dive-example
base: bare
build-base: ubuntu@24.04
version: '0.1'
summary: summary
description: | …
```
> feat: split dive tests to allow fails in highestUserWastedPercent

- .github/workflows/Rebuild-Images.yaml
- oci/mock-rock/_releases.json
- tools/workflow-engine/charms/temporal-worker/oci_factory/activities/find_images_to_update.py
---
This PR includes:
- A slight refactoring of the `find_images_to_update.py`, to make it able to trigger image rebuilds based on Ubuntu releases __and image names__.
- A new workflow that rebuilds images daily. `mock-rock` will have daily rebuilds for now. The other rocks will received this once the daily rebuild for `mock-rock` is verified to work well.
N/A
> feat(ci): enable daily rebuild for rocks

- oci/parca/.trivyignore
---
We used `govulncheck` to verify that parca is not affected by https://github.com/advisories/GHSA-mh63-6h87-95cp . 
https://github.com/canonical/parca-rock/issues/6
---
> chore: Add CVE-2025-30204 to trivyignore for parca

- oci/node-exporter/contacts.yaml
- oci/node-exporter/documentation.yaml
- oci/node-exporter/image.yaml
---
Adds an initial version of the node-exporter rock
#413 
---
*Picture of cool rock:*
> add node exporter oci image v 1.9.1

- .github/workflows/Rebuild-Images.yaml
- oci/mock-rock/_releases.json
- tools/workflow-engine/charms/temporal-worker/oci_factory/activities/find_images_to_update.py
---
This PR adds an external reference id for the Image workflow triggered by daily rebuilds.
https://github.com/canonical/oci-factory/actions/runs/14467743435/attempts/1#summary-40573979209
> feat(ci): daily rebuild with its own ext ref id prefix

- .github/workflows/Test-Rock.yaml
- oci/mock-rock/_releases.json
---
When running `umoci`, it uses an oci-factory custom action, by relative path. But it's cloning the repo that calls the workflow, when it should checkout the oci-factory repo.
Fixes https://github.com/canonical/age-rock/actions/runs/15248442623/job/42882190396
---
> fix(Test-Rock): need to checkout oci-factory and not target repo

- .github/workflows/Release.yaml
- oci/mock-rock/_releases.json
This can only be properly tested in `main`, since that's where the branch protection rules are constraining our workflows
> fix(ci): have the rocksbot force push to bypass branch protection

- .github/workflows/Rebuild-Images.yaml
- oci/mock-rock/_releases.json
---
This PR enables the weekly rebuild for all the rocks. Rebuild occurs on Sundays to avoid surges in runners on weekdays.
> feat(ci): enable weekly rebuild for all images

- oci/dotnet-runtime/contacts.yaml
- oci/dotnet-runtime/documentation.yaml
- oci/dotnet-runtime/image.yaml
---
This PR adds the dotnet-runtime:9.0-25.04_edge.
The documentation is handled similarly to the `jre` rock to cope with the co-existence of Dockerfile-based images and rocks.
#517
> feat: add dotnet-runtime:9.0-25.04_edge

- src/docs/generate_oci_doc_yaml.py
- src/docs/schema/triggers.py
---
This PR adds the feature to generate the documentation with the correct EOL dates for legacy images and for images having mismatched build-base and tracks (e.g., for `dotnet:9.0-25.04`, which is built on `24.04` as a build-base).
N/A
---
> feat(ci): support legacy images in documentation for proper EOL

- oci/litmuschaos-server/.trivyignore
- oci/litmuschaos-server/image.yaml
---
- Add a new 3.20.0 release.
- Add vuln to .trivyignore after validating with govulncheck
---
> chore: Add new litmuschaos-server releases

- .github/workflows/Build-Rock.yaml
- .github/workflows/Test-Rock.yaml
- README.md
---
This PR removes the calling into `get-workflow-version-action,` in order to limit the calls into GH API, which often causes the rate limit to be exceeded.
Note: We have to keep the security input of `host-github-token` for now, but mark it as deprecated for now to continue supporting the other repos that pass the `host-github-token` secret into the corresponding workflows.
N/A
[Workflow run a private repo](https://github.com/canonical/test-private-templated-rock/actions/runs/17496210544) demonstrates that the `host-github-token`  is not needed anymore, and the workflow runs correctly without the `get-workflow-version-action` being called.
---
> feat(ci): remove get workflow version action
